### PR TITLE
Include sysName to output

### PR DESCRIPTION
**Pull request by alexwbaule**
Hi, i include the "sysName" to the output.

This is valid to split each switch, router, etc by "name" , if you have a lot of them in the network.

### CODE REVIEW

**Comment by majormoses** [comment]
@alexwbaule can you look at failing CI and fix it up before review?

**Comment by alexwbaule** [comment]
Ok, Fix the Tabs ? It's the only error that CI fails...

**Comment by majormoses** [comment]
yes, I just took a quick peak and its mostly spacing/tabbing. I honestly often do not review the code in a PR until the tests pass as often we ask people to fix stuff and they sometimes do not and then end up closing them out many months (or years later).

**Comment by majormoses** [comment]
@alexwbaule any chance of picking this back up? If not I am gonna close this out (I might take your commits and fix them up if I have time)

**Comment by majormoses** [comment]
closing due to inactivity, please reply back if you would like to see this through so I can re-open.

**Pull request closed without merging**
