### PR TITLE
Add config file based snmp metrics plugin

### PR DESCRIPTION
**Pull request by jaimegago**
## Pull Request Checklist

**Is this in reference to an existing issue?** NO
#### General
- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [X] Update README with any necessary configuration snippets
- [ ] Binstubs are created if needed
- [ ] RuboCop passes : PYTHON
- [X] Existing tests pass 
#### New Plugins
- [ ] Tests
- [X] Add the plugin to the README
- [X] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)
#### Purpose

A plugin that allows to specify multiple OIDs for one device and grab metrics from it via a single sensu metrics check. Current SNMP plugin only allows to specify one OID.
#### Known Compatibility Issues

Depends on easysnmp  python module which is not standard.
No unit test provided, would that even work considering they would be python tests?
Overall the "over" friendliness towards ruby plugins (docs, PR template, repo structure, linting,...) is kinda acting as a deterrent for pythonistas like me that have already contributed a couple of Python sensu plugins. The capability to execute scripts in any language is a major advantage of Sensu and should IMHO be advertised through the sensu plugins. Happy to help on the "hey you can also contribute python plugins!" evangelization if need be.

### CODE REVIEW

**Comment by analytically** [comment]
Would you be able to rewrite this in Ruby?

**Comment by jaimegago** [comment]
this in Ruby =P

**Comment by analytically** [comment]
You start the file with `#!/usr/bin/env python` and the file is named .py...

**Comment by jaimegago** [comment]
@analytically I'm sorry, are we actually having a serious conversation related to this PR ? If we are I'm afraid I don't understand your points otherwise I'm afraid I'm not getting the joke anymore. Thus I'm going to rewind and assume you are  being serious.
- "Rewrite in Ruby" : I could but why would I? This plugin works and unless I missed something there is no "Sensu Community Plugins" should be written in Ruby rule or is there now? (I really thought you were kidding about this)
- "You start the file with #!/usr/bin/env python and the file is named .py" ? This python shbang is a pretty standard one, the .py extension is to follow with the requirements that plugins needed the language extension, maybe this is not required anymore? Please expand on what is wrong with this.

I think there must have been a misunderstanding maybe even from the start of this PR, if you think we can understand each other and have the time for it please go on, other wise please go ahead and reject the PR I won't take it personally I promise ;-).

**Comment by analytically** [comment]
We prefer contributions in Ruby, since there are issues deploying plugins with python scripts. So, since it's only about 100 lines, I ask if you would be able to rewrite this in Ruby. If not, I'm afraid I can't merge this PR and other members of the team can decide.

**Comment by jaimegago** [comment]
Ahhh makes sense now! I missed the boat on Ruby becoming the de facto language for plugins contribution and issues with deploying Python plugins but then I'm still managing "my" sensu plugins the old way by cherry picking so this explain that. I'll just keep the Python plugins I've written in a personal repo no biggy. From where I stand though standardizing on one language for the official plugins seems counter intuitive but hey you guys must have your reasons!

**Pull request closed without merging**
